import numpy as np

In [6]:
import numpy as np
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [8]:
np.full((5,4),2.5)

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
x=np.full((3,5),9)

In [16]:
x

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [17]:
x.ndim

2

In [18]:
x.shape

(3, 5)

In [19]:
x.dtype

dtype('int32')

In [36]:
n3=np.array([[7,7,7],[1,1,1]])

In [37]:
n3

array([[7, 7, 7],
       [1, 1, 1]])

In [38]:
n3.shape

(2, 3)

In [39]:
n3.ndim

2

In [40]:
l=np.random.random(9)

In [41]:
l

array([0.27343213, 0.00137867, 0.80542382, 0.73272252, 0.42867906,
       0.28459652, 0.26613149, 0.32337315, 0.29192554])

In [42]:
np.sum(l)

3.4076629060659007

In [45]:
%timeit sum(l)

2.66 µs ± 180 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [46]:
%timeit np.sum(l)

5.25 µs ± 524 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
