In [32]:
import numpy as np
from numpy import linalg



In [33]:
matrix=np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [34]:
type(matrix)

numpy.ndarray

In [35]:
#inverse of a matrix
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [36]:
#detrminant
linalg.det(matrix)

58.000000000000036

In [37]:
num_arr=np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [38]:
num_arrVal=np.array([21,9,6])

In [39]:
linalg.solve(num_arr,num_arrVal)

array([ 4.95,  4.35, -1.95])

In [40]:
num2_arr=np.array([[3,5,1],[9,5,7]])

In [41]:
num2_arr.shape

(2, 3)

In [42]:
#single value decomposition
linalg.svd(num2_arr)

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

In [43]:
#test rating matrix rating on a scale of 10
testData=np.array([[5,8],[7,9]])
eigenValue,eigenVector=linalg.eig(testData)
first_eigen,second_eigen=eigenValue



In [44]:
print(first_eigen,second_eigen)

-0.745966692414834 14.745966692414834


In [45]:
#first eigen vector
print(eigenVector[:,0])

[-0.81220939  0.58336601]


In [46]:
#second eigen vector
print(eigenVector[:,1])

[-0.63447346 -0.77294465]
